#!/usr/bin/env bash
# ==============================================================================
# RECON7 — DEFENSE-GRADE INTERACTIVE DEPLOYMENT WIZARD (Linux / macOS)
# Ojabo Organization • Attack Surface Intelligence Platform
# Docker Repository: johnojabo1/recon7
# ==============================================================================

set -e

# Terminal Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
echo "  ██████╗ ███████╗██████╗ ██████╗ ███╗   ██╗███████╗"
echo "  ██╔══██╗██╔════╝██╔════╝██╔═══██╗████╗  ██║╚════██║"
echo "  ██████╔╝█████╗  ██║     ██║   ██║██╔██╗ ██║    ██╔╝"
echo "  ██╔══██╗██╔══╝  ██║     ██║   ██║██║╚██╗██║   ██╔╝ "
echo "  ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║   ██║  "
echo "  ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝  "
echo -e "${NC}"
echo -e "${YELLOW}ENTERPRISE DEPLOYMENT WIZARD${NC}"
echo "--------------------------------------------------------"
echo "This installer configures your environment credentials, builds"
echo "the unified Recon7 container (johnojabo1/recon7), and deploys"
echo "the complete stack (Web Console + API + Worker + PostgreSQL)."
echo ""

# 1. Check Docker & Docker Compose installation
if ! command -v docker &> /dev/null; then
    echo -e "${RED}[ERROR] Docker is not installed or not in PATH. Please install Docker first.${NC}"
    exit 1
fi

if ! docker compose version &> /dev/null && ! command -v docker-compose &> /dev/null; then
    echo -e "${RED}[ERROR] Docker Compose is not installed. Please install Docker Compose first.${NC}"
    exit 1
fi

DOCKER_COMPOSE_CMD="docker compose"
if ! docker compose version &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"
fi

# 2. Database Password
echo -e "${CYAN}[Step 1/4] Database Security Credentials${NC}"
echo -e "${YELLOW}Tip: Press ENTER to use default password ('reconpassword123').${NC}"
read -s -p "Enter PostgreSQL password [Press ENTER for default]: " INPUT_DB_PASS
echo ""
POSTGRES_PASSWORD=${INPUT_DB_PASS:-reconpassword123}
echo -e "${GREEN}Database password configured.${NC}"
echo ""

# 3. Operational Environment & Security Scopes
echo -e "${CYAN}[Step 2/4] Scope Authorization Settings${NC}"
echo -e "${YELLOW}Tip: Press ENTER to keep strict production security ('false').${NC}"
echo "Setting to 'true' bypasses target pre-approval for rapid local dev testing."
read -p "Allow dev scope bypass? (true/false) [Press ENTER for default 'false']: " INPUT_SCOPE_DEV
ALLOW_ALL_SCOPES_DEV=${INPUT_SCOPE_DEV:-false}
echo -e "${GREEN}Scope Bypass set to: ${ALLOW_ALL_SCOPES_DEV}${NC}"
echo ""

# 4. Optional Integrations Credentials
echo -e "${CYAN}[Step 3/4] Optional External API Keys${NC}"
echo -e "${YELLOW}Tip: If you do not have API keys right now, press ENTER on each prompt to skip.${NC}"
echo "Recon7 runs core features out of the box using free passive sources without API keys."
echo ""
read -p "GitHub Token (Optional - Press ENTER to skip): " GITHUB_TOKEN
read -p "Google Search API Key (Optional - Press ENTER to skip): " GOOGLE_SEARCH_API_KEY
read -p "Google Search Engine ID (Optional - Press ENTER to skip): " GOOGLE_SEARCH_ENGINE_ID
echo ""

# Write .env file
echo -e "${CYAN}[Step 4/4] Generating .env configuration and launching containers...${NC}"

cat <<EOF > .env
# Auto-generated by Recon7 Installation Wizard
ENVIRONMENT=production
DEBUG=False

# Database Configuration
POSTGRES_DB=recon7
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/recon7

# Scope Authorization Gate
ALLOW_ALL_SCOPES_DEV=${ALLOW_ALL_SCOPES_DEV}

# OSINT Credentials
GITHUB_TOKEN=${GITHUB_TOKEN}
GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID}
EOF

echo -e "${GREEN}✓ Configuration saved to .env${NC}"
echo ""

# Build & Deploy Containers
echo -e "${YELLOW}Building unified Docker image (johnojabo1/recon7) and starting services...${NC}"
${DOCKER_COMPOSE_CMD} build
${DOCKER_COMPOSE_CMD} up -d

echo ""
echo -e "${GREEN}========================================================${NC}"
echo -e "${GREEN}  RECON7 PLATFORM DEPLOYED SUCCESSFULLY! ${NC}"
echo -e "${GREEN}========================================================${NC}"
echo ""
echo "Operational Endpoints:"
echo " - Web Console UI:   http://localhost:8000 (or http://YOUR_SERVER_IP:8000)"
echo " - REST API & Docs:  http://localhost:8000/docs"
echo " - Health Status:    http://localhost:8000/health"
echo ""
echo "To monitor container logs: ${DOCKER_COMPOSE_CMD} logs -f"
echo "To stop containers:        ${DOCKER_COMPOSE_CMD} down"
echo ""
