#!/usr/bin/env bash
# ==============================================================================
# RECON7 — DEFENSE-GRADE INTERACTIVE DEPLOYMENT WIZARD (Linux / macOS)
# Ojabo Organization • Attack Surface Intelligence Platform
# ==============================================================================

set -e

# Terminal Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
echo "  ██████╗ ███████╗██████╗ ██████╗ ███╗   ██╗███████╗"
echo "  ██╔══██╗██╔════╝██╔════╝██╔═══██╗████╗  ██║╚════██║"
echo "  ██████╔╝█████╗  ██║     ██║   ██║██╔██╗ ██║    ██╔╝"
echo "  ██╔══██╗██╔══╝  ██║     ██║   ██║██║╚██╗██║   ██╔╝ "
echo "  ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║   ██║  "
echo "  ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝  "
echo -e "${NC}"
echo -e "${YELLOW}DEFENSE-GRADE INTERACTIVE DEPLOYMENT WIZARD${NC}"
echo "--------------------------------------------------------"
echo "This installer will configure your environment build arguments,"
echo "generate secure production credentials, build container images,"
echo "and deploy the Recon7 stack using Docker Compose."
echo ""

# 1. Check Docker & Docker Compose installation
if ! command -v docker &> /dev/null; then
    echo -e "${RED}[ERROR] Docker is not installed or not in PATH. Please install Docker first.${NC}"
    exit 1
fi

if ! docker compose version &> /dev/null && ! command -v docker-compose &> /dev/null; then
    echo -e "${RED}[ERROR] Docker Compose is not installed. Please install Docker Compose first.${NC}"
    exit 1
fi

DOCKER_COMPOSE_CMD="docker compose"
if ! docker compose version &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"
fi

# 2. Interactive Frontend API Base URL (Crucial for LAN / Internet deployments)
echo -e "${CYAN}[Step 1/5] Frontend API Base URL Configuration${NC}"
echo "Single Page Applications (Vite React) execute inside the client's browser."
echo "If accessing Recon7 across a LAN, VPN, or public Internet, the browser cannot reach container names (e.g. r7-api)."
echo ""
echo "Options:"
echo " 1) /api  (Recommended: Relative Nginx proxy — works automatically across LAN & Domain IP)"
echo " 2) http://YOUR_SERVER_IP:8000 (Direct IP access)"
echo " 3) https://api.yourdomain.com (Custom public domain)"
echo ""

read -p "Enter API Base URL [default: /api]: " INPUT_API_URL
VITE_API_URL=${INPUT_API_URL:-/api}
echo -e "${GREEN}✓ Frontend API URL set to: ${VITE_API_URL}${NC}"
echo ""

# 3. PostgreSQL Database Password
echo -e "${CYAN}[Step 2/5] Database Security Credentials${NC}"
read -s -p "Enter PostgreSQL password [default: reconpassword123]: " INPUT_DB_PASS
echo ""
POSTGRES_PASSWORD=${INPUT_DB_PASS:-reconpassword123}
echo -e "${GREEN}✓ Database password configured.${NC}"
echo ""

# 4. Operational Environment & Security Scopes
echo -e "${CYAN}[Step 3/5] Environment & Authorization Gate Settings${NC}"
read -p "Allow dev scope bypass? (true/false) [default: false]: " INPUT_SCOPE_DEV
ALLOW_ALL_SCOPES_DEV=${INPUT_SCOPE_DEV:-false}
echo -e "${GREEN}✓ Scope Bypass set to: ${ALLOW_ALL_SCOPES_DEV}${NC}"
echo ""

# 5. Optional Integrations Credentials
echo -e "${CYAN}[Step 4/5] Optional OSINT Credentials (Press ENTER to skip)${NC}"
read -p "GitHub Personal Access Token (for 5,000 req/hr quota): " GITHUB_TOKEN
read -p "Google Search API Key: " GOOGLE_SEARCH_API_KEY
read -p "Google Search Engine ID (CX): " GOOGLE_SEARCH_ENGINE_ID
echo ""

# Write .env file
echo -e "${CYAN}[Step 5/5] Generating .env configuration and launching containers...${NC}"

cat <<EOF > .env
# Auto-generated by Recon7 Installation Wizard
ENVIRONMENT=production
DEBUG=False
VITE_API_URL=${VITE_API_URL}

# Database Configuration
POSTGRES_DB=recon7
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/recon7

# Scope Authorization Gate
ALLOW_ALL_SCOPES_DEV=${ALLOW_ALL_SCOPES_DEV}

# OSINT Credentials
GITHUB_TOKEN=${GITHUB_TOKEN}
GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID}
EOF

echo -e "${GREEN}✓ Configuration saved to .env${NC}"
echo ""

# Build & Deploy Containers
echo -e "${YELLOW}Building Docker images and starting services...${NC}"
VITE_API_URL="${VITE_API_URL}" ${DOCKER_COMPOSE_CMD} build --build-arg VITE_API_URL="${VITE_API_URL}"
${DOCKER_COMPOSE_CMD} up -d

echo ""
echo -e "${GREEN}========================================================${NC}"
echo -e "${GREEN}  RECON7 PLATFORM DEPLOYED SUCCESSFULLY! ${NC}"
echo -e "${GREEN}========================================================${NC}"
echo ""
echo "Operational Endpoints:"
echo " - Web Console UI:   http://localhost:5173 (or http://SERVER_IP)"
echo " - REST API Server:  http://localhost:8000 (or ${VITE_API_URL})"
echo " - Swagger Docs:     http://localhost:8000/docs"
echo ""
echo "To monitor container logs: ${DOCKER_COMPOSE_CMD} logs -f"
echo "To stop containers:        ${DOCKER_COMPOSE_CMD} down"
echo ""
