# ==============================================================================
# RECON7 — DEFENSE-GRADE INTERACTIVE DEPLOYMENT WIZARD (Windows PowerShell)
# Ojabo Organization • Attack Surface Intelligence Platform
# ==============================================================================

$ErrorActionPreference = "Stop"

Write-Host "  ██████╗ ███████╗██████╗ ██████╗ ███╗   ██╗███████╗" -ForegroundColor Cyan
Write-Host "  ██╔══██╗██╔════╝██╔════╝██╔═══██╗████╗  ██║╚════██║" -ForegroundColor Cyan
Write-Host "  ██████╔╝█████╗  ██║     ██║   ██║██╔██╗ ██║    ██╔╝" -ForegroundColor Cyan
Write-Host "  ██╔══██╗██╔══╝  ██║     ██║   ██║██║╚██╗██║   ██╔╝ " -ForegroundColor Cyan
Write-Host "  ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║   ██║  " -ForegroundColor Cyan
Write-Host "  ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝  " -ForegroundColor Cyan
Write-Host ""
Write-Host "DEFENSE-GRADE INTERACTIVE DEPLOYMENT WIZARD" -ForegroundColor Yellow
Write-Host "--------------------------------------------------------"
Write-Host "This installer will configure environment build arguments,"
Write-Host "generate secure production credentials, build container images,"
Write-Host "and deploy the Recon7 stack using Docker Compose."
Write-Host ""

# 1. Verify Docker CLI availability
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "[ERROR] Docker is not installed or not available in PATH." -ForegroundColor Red
    exit 1
}

# 2. Interactive Frontend API Base URL
Write-Host "[Step 1/5] Frontend API Base URL Configuration" -ForegroundColor Cyan
Write-Host "Single Page Applications (Vite React) execute inside the client's browser."
Write-Host "If accessing Recon7 across a LAN, VPN, or public Internet, the browser cannot reach container names (e.g. r7-api)."
Write-Host ""
Write-Host "Options:"
Write-Host " 1) /api  (Recommended: Relative Nginx proxy — works automatically across LAN & Domain IP)"
Write-Host " 2) http://YOUR_SERVER_IP:8000 (Direct IP access)"
Write-Host " 3) https://api.yourdomain.com (Custom public domain)"
Write-Host ""

$inputApiUrl = Read-Host "Enter API Base URL [default: /api]"
$viteApiUrl = if ([string]::IsNullOrWhiteSpace($inputApiUrl)) { "/api" } else { $inputApiUrl }
Write-Host "✓ Frontend API URL set to: $viteApiUrl" -ForegroundColor Green
Write-Host ""

# 3. Database Password
Write-Host "[Step 2/5] Database Security Credentials" -ForegroundColor Cyan
$inputDbPass = Read-Host "Enter PostgreSQL password [default: reconpassword123]"
$postgresPassword = if ([string]::IsNullOrWhiteSpace($inputDbPass)) { "reconpassword123" } else { $inputDbPass }
Write-Host "✓ Database password configured." -ForegroundColor Green
Write-Host ""

# 4. Environment Mode & Dev Scope Bypass
Write-Host "[Step 3/5] Environment & Authorization Gate Settings" -ForegroundColor Cyan
$inputScopeDev = Read-Host "Allow dev scope bypass? (true/false) [default: false]"
$allowAllScopesDev = if ([string]::IsNullOrWhiteSpace($inputScopeDev)) { "false" } else { $inputScopeDev }
Write-Host "✓ Scope Bypass set to: $allowAllScopesDev" -ForegroundColor Green
Write-Host ""

# 5. Optional Integrations Credentials
Write-Host "[Step 4/5] Optional OSINT Credentials (Press ENTER to skip)" -ForegroundColor Cyan
$githubToken = Read-Host "GitHub Personal Access Token (for 5,000 req/hr quota)"
$googleApiKey = Read-Host "Google Search API Key"
$googleEngineId = Read-Host "Google Search Engine ID (CX)"
Write-Host ""

# Write .env file
Write-Host "[Step 5/5] Generating .env configuration and launching containers..." -ForegroundColor Cyan

$envContent = @"
# Auto-generated by Recon7 Installation Wizard
ENVIRONMENT=production
DEBUG=False
VITE_API_URL=$viteApiUrl

# Database Configuration
POSTGRES_DB=recon7
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$postgresPassword
DATABASE_URL=postgresql://postgres:${postgresPassword}@postgres:5432/recon7

# Scope Authorization Gate
ALLOW_ALL_SCOPES_DEV=$allowAllScopesDev

# OSINT Credentials
GITHUB_TOKEN=$githubToken
GOOGLE_SEARCH_API_KEY=$googleApiKey
GOOGLE_SEARCH_ENGINE_ID=$googleEngineId
"@

$envContent | Out-File -FilePath ".env" -Encoding utf8
Write-Host "✓ Configuration saved to .env" -ForegroundColor Green
Write-Host ""

# Build & Deploy Containers
Write-Host "Building Docker images and starting services..." -ForegroundColor Yellow
$env:VITE_API_URL = $viteApiUrl
docker compose build --build-arg VITE_API_URL=$viteApiUrl
docker compose up -d

Write-Host ""
Write-Host "========================================================" -ForegroundColor Green
Write-Host "  RECON7 PLATFORM DEPLOYED SUCCESSFULLY! " -ForegroundColor Green
Write-Host "========================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Operational Endpoints:"
Write-Host " - Web Console UI:   http://localhost:5173 (or http://SERVER_IP)"
Write-Host " - REST API Server:  http://localhost:8000 (or $viteApiUrl)"
Write-Host " - Swagger Docs:     http://localhost:8000/docs"
Write-Host ""
Write-Host "To monitor container logs: docker compose logs -f"
Write-Host "To stop containers:        docker compose down"
Write-Host ""
