# ==============================================================================
# RECON7 — DEFENSE-GRADE INTERACTIVE DEPLOYMENT WIZARD (Windows PowerShell)
# Ojabo Organization • Attack Surface Intelligence Platform
# Docker Repository: johnojabo1/recon7
# ==============================================================================

$ErrorActionPreference = "Stop"

Write-Host "  ██████╗ ███████╗██████╗ ██████╗ ███╗   ██╗███████╗" -ForegroundColor Cyan
Write-Host "  ██╔══██╗██╔════╝██╔════╝██╔═══██╗████╗  ██║╚════██║" -ForegroundColor Cyan
Write-Host "  ██████╔╝█████╗  ██║     ██║   ██║██╔██╗ ██║    ██╔╝" -ForegroundColor Cyan
Write-Host "  ██╔══██╗██╔══╝  ██║     ██║   ██║██║╚██╗██║   ██╔╝ " -ForegroundColor Cyan
Write-Host "  ██║  ██║███████╗╚██████╗╚██████╔╝██║ ╚████║   ██║  " -ForegroundColor Cyan
Write-Host "  ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝  " -ForegroundColor Cyan
Write-Host ""
Write-Host "ENTERPRISE DEPLOYMENT WIZARD" -ForegroundColor Yellow
Write-Host "--------------------------------------------------------"
Write-Host "This installer configures your environment credentials, builds"
Write-Host "the unified Recon7 container (johnojabo1/recon7), and deploys"
Write-Host "the complete stack (Web Console + API + Worker + PostgreSQL)."
Write-Host ""

# 1. Verify Docker CLI availability
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "[ERROR] Docker is not installed or not available in PATH." -ForegroundColor Red
    exit 1
}

# 2. Database Password
Write-Host "[Step 1/4] Database Security Credentials" -ForegroundColor Cyan
Write-Host "Tip: Press ENTER to use default password ('reconpassword123')." -ForegroundColor Yellow
$inputDbPass = Read-Host "Enter PostgreSQL password [Press ENTER for default]"
$postgresPassword = if ([string]::IsNullOrWhiteSpace($inputDbPass)) { "reconpassword123" } else { $inputDbPass }
Write-Host "Database password configured." -ForegroundColor Green
Write-Host ""

# 3. Environment Mode & Dev Scope Bypass
Write-Host "[Step 2/4] Scope Authorization Settings" -ForegroundColor Cyan
Write-Host "Tip: Press ENTER to keep strict production security ('false')." -ForegroundColor Yellow
Write-Host "Setting to 'true' bypasses target pre-approval for rapid local dev testing."
$inputScopeDev = Read-Host "Allow dev scope bypass? (true/false) [Press ENTER for default 'false']"
$allowAllScopesDev = if ([string]::IsNullOrWhiteSpace($inputScopeDev)) { "false" } else { $inputScopeDev }
Write-Host "Scope Bypass set to: $allowAllScopesDev" -ForegroundColor Green
Write-Host ""

# 4. Optional Integrations Credentials
Write-Host "[Step 3/4] Optional External API Keys" -ForegroundColor Cyan
Write-Host "Tip: If you do not have API keys right now, press ENTER on each prompt to skip." -ForegroundColor Yellow
Write-Host "Recon7 runs core features out of the box using free passive sources without API keys."
Write-Host ""
$githubToken = Read-Host "GitHub Token (Optional - Press ENTER to skip)"
$googleApiKey = Read-Host "Google Search API Key (Optional - Press ENTER to skip)"
$googleEngineId = Read-Host "Google Search Engine ID (Optional - Press ENTER to skip)"
Write-Host ""

# Write .env file
Write-Host "[Step 4/4] Generating .env configuration and launching containers..." -ForegroundColor Cyan

$envContent = @"
# Auto-generated by Recon7 Installation Wizard
ENVIRONMENT=production
DEBUG=False

# Database Configuration
POSTGRES_DB=recon7
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$postgresPassword
DATABASE_URL=postgresql://postgres:${postgresPassword}@postgres:5432/recon7

# Scope Authorization Gate
ALLOW_ALL_SCOPES_DEV=$allowAllScopesDev

# OSINT Credentials
GITHUB_TOKEN=$githubToken
GOOGLE_SEARCH_API_KEY=$googleApiKey
GOOGLE_SEARCH_ENGINE_ID=$googleEngineId
"@

$envContent | Out-File -FilePath ".env" -Encoding utf8
Write-Host "✓ Configuration saved to .env" -ForegroundColor Green
Write-Host ""

# Build & Deploy Containers
Write-Host "Building unified Docker image (johnojabo1/recon7) and starting services..." -ForegroundColor Yellow
docker compose build
docker compose up -d

Write-Host ""
Write-Host "========================================================" -ForegroundColor Green
Write-Host "  RECON7 PLATFORM DEPLOYED SUCCESSFULLY! " -ForegroundColor Green
Write-Host "========================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Operational Endpoints:"
Write-Host " - Web Console UI:   http://localhost:8000 (or http://YOUR_SERVER_IP:8000)"
Write-Host " - REST API & Docs:  http://localhost:8000/docs"
Write-Host " - Health Status:    http://localhost:8000/health"
Write-Host ""
Write-Host "To monitor container logs: docker compose logs -f"
Write-Host "To stop containers:        docker compose down"
Write-Host ""
