import pytest
import io
import zipfile
import xml.etree.ElementTree as ET
from people.doc_metadata import (
    _extract_pdf_forensics,
    _extract_openxml_forensics,
    AD_USER_REGEX,
    UNC_PATH_REGEX,
)


def test_ad_username_regex():
    sample_text = "Generated by CORP\\jdoe for administrator alex.turner_adm and user CORP\\finance_user."
    matches = AD_USER_REGEX.findall(sample_text)
    assert len(matches) >= 2
    assert "CORP\\jdoe" in matches
    assert "alex.turner_adm" in matches or "CORP\\finance_user" in matches


def test_unc_path_regex():
    sample_text = "Stored on \\\\fileserver01.corp.internal\\Accounting\\Q4_Payroll.xlsx and local path C:\\Users\\jdoe\\Documents\\Report.docx"
    matches = UNC_PATH_REGEX.findall(sample_text)
    assert len(matches) >= 2
    assert "\\\\fileserver01.corp.internal\\Accounting\\Q4_Payroll.xlsx" in matches
    assert "C:\\Users\\jdoe\\Documents\\Report.docx" in matches


def test_openxml_forensics_extraction():
    # Build in-memory mock DOCX/OpenXML zip package
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as z:
        # docProps/core.xml
        core_xml_content = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/">
            <dc:creator>Alice Vance</dc:creator>
            <cp:lastModifiedBy>Bob Admin</cp:lastModifiedBy>
            <cp:created>2024-05-10T14:30:00Z</cp:created>
        </cp:coreProperties>"""
        z.writestr("docProps/core.xml", core_xml_content)

        # docProps/app.xml
        app_xml_content = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">
            <Application>Microsoft Word</Application>
            <AppVersion>16.0000</AppVersion>
            <Company>Acme Corporation</Company>
        </Properties>"""
        z.writestr("docProps/app.xml", app_xml_content)

        # word/document.xml
        doc_xml_content = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
            <w:body>
                <w:p><w:r><w:t>Confidential internal review prepared by CORP\\avance.</w:t></w:r></w:p>
            </w:body>
        </w:document>"""
        z.writestr("word/document.xml", doc_xml_content)

    zip_bytes = zip_buffer.getvalue()
    body_text, meta = _extract_openxml_forensics(zip_bytes)

    assert meta["author"] == "Alice Vance"
    assert meta["last_modified_by"] == "Bob Admin"
    assert meta["creator_software"] == "Microsoft Word"
    assert meta["software_version"] == "16.0000"
    assert "CORP\\avance" in body_text
