import json
import logging
from typing import Dict, Any, List

logger = logging.getLogger(__name__)


def generate_engagement_report(scan_job_data: Dict[str, Any], triage_data: Dict[str, Any]) -> str:
    """
    Step 10: Turns structured findings and triage output into a full, human-readable
    Markdown executive and technical engagement report.
    """
    domain = scan_job_data.get("target_domain", "Unknown")
    org_info = scan_job_data.get("company_info", {})
    subdomains = scan_job_data.get("subdomains", [])
    ip_resolutions = scan_job_data.get("ip_resolutions", [])
    ports = scan_job_data.get("ports", [])
    fingerprints = scan_job_data.get("fingerprints", [])
    vulns = scan_job_data.get("vulns", [])
    people = scan_job_data.get("people", {})

    executive_summary = triage_data.get("executive_summary", "Comprehensive attack-surface reconnaissance completed.")
    prioritized_findings = triage_data.get("prioritized_findings", [])
    attack_vectors = triage_data.get("attack_vectors", [])

    lines = []
    lines.append(f"# Reconnaissance & Attack-Surface Assessment: {domain}")
    lines.append(f"**Generated by R7 (Reconnaissance 7) Platform** | *Authorized Red Team Operations*\n")
    lines.append("---\n")

    # 1. Executive Summary
    lines.append("## 1. Executive Summary")
    lines.append(executive_summary + "\n")

    # 2. Scope & Target Infrastructure Metadata
    lines.append("## 2. Organization & Target Infrastructure")
    lines.append(f"- **Target Domain:** `{domain}`")
    lines.append(f"- **Organization Name:** {org_info.get('org_name', 'Unknown')}")
    lines.append(f"- **ASN / Network:** {org_info.get('asn', 'N/A')} ({org_info.get('asn_description', 'N/A')})")
    lines.append(f"- **Registrar:** {org_info.get('registrar', 'N/A')}")
    lines.append(f"- **Nameservers:** {', '.join(org_info.get('nameservers', [])) or 'N/A'}")
    lines.append(f"- **Primary IP(s):** {', '.join(org_info.get('primary_ips', [])) or 'N/A'}\n")

    # 3. Attack Surface Topology & Asset Discovery
    lines.append("## 3. Attack Surface & Asset Discovery")
    lines.append(f"Discovered **{len(subdomains)}** subdomains and **{len(ip_resolutions)}** active hosts.\n")

    lines.append("### 3.1 Active Hosts & CDN Segregation")
    lines.append("| Subdomain | Resolved IP(s) | CDN / Edge WAF | Provider |")
    lines.append("|---|---|---|---|")
    for host in ip_resolutions[:30]:
        ips_str = ", ".join(host.get("ips", [])) or "CNAME only"
        cdn_str = "Yes" if host.get("is_cdn") else "Direct Origin"
        provider_str = host.get("cdn_provider") or "N/A"
        lines.append(f"| `{host.get('subdomain')}` | `{ips_str}` | {cdn_str} | {provider_str} |")
    lines.append("\n")

    # 4. Open Ports & Services
    lines.append("### 3.2 Open Ports & Service Fingerprints")
    if ports:
        lines.append("| Port | Protocol | Service | Product | Version |")
        lines.append("|---|---|---|---|---|")
        for p in ports[:30]:
            lines.append(f"| `{p.get('port')}` | {p.get('protocol', 'tcp').upper()} | {p.get('service', 'unknown')} | {p.get('product', '')} | {p.get('version', '')} |")
    else:
        lines.append("*No open TCP services discovered on probed targets.*")
    lines.append("\n")

    # 5. Technology Stack
    lines.append("### 3.3 Technology Stack Matrix")
    if fingerprints:
        lines.append("| Asset URL | Web Server | Detected Technologies |")
        lines.append("|---|---|---|")
        for fp in fingerprints[:20]:
            tech_names = ", ".join([f"{t.get('name')} {t.get('version', '')}".strip() for t in fp.get("technologies", [])])
            lines.append(f"| [{fp.get('url')}]({fp.get('url')}) | {fp.get('web_server', 'unknown')} | {tech_names or 'Standard Web'} |")
    else:
        lines.append("*No active HTTP web applications identified.*")
    lines.append("\n")

    # 6. Prioritized Findings & Vulnerabilities
    lines.append("## 4. Prioritized Vulnerability & Risk Matrix")
    if prioritized_findings:
        for find in prioritized_findings:
            sev = find.get("severity", "info").upper()
            tier_badge = "[ACTIVE EXPLOIT PROOF]" if find.get("evidence_tier") == "ACTIVE_EXPLOIT_PROOF" else "[VERSION ADVISORY]"
            lines.append(f"### [{sev}] {find.get('title')} {tier_badge}")
            lines.append(f"- **Affected Asset:** `{find.get('affected_asset')}`")
            lines.append(f"- **Risk Score:** {find.get('risk_score', 'N/A')}/10")
            lines.append(f"- **Evidence & Rationale:** {find.get('rationale')}")
            lines.append(f"- **Recommended Action:** {find.get('recommendation')}\n")
    elif vulns:
        for v in vulns[:15]:
            sev = v.get("severity", "info").upper()
            tier_badge = "[ACTIVE EXPLOIT PROOF]" if v.get("evidence_tier") == "ACTIVE_EXPLOIT_PROOF" or v.get("status") == "confirmed" else "[VERSION ADVISORY]"
            lines.append(f"### [{sev}] {v.get('title') or v.get('name')} {tier_badge}")
            lines.append(f"- **Host:** `{v.get('host')}` | **Matched At:** `{v.get('matched_at') or v.get('host')}`")
            lines.append(f"- **OWASP Category:** {v.get('owasp_category', 'General')}")
            lines.append(f"- **Description:** {v.get('description')}")
            if v.get("remediation"):
                lines.append(f"- **Remediation:** {v.get('remediation')}")
            lines.append("")
    else:
        lines.append("*No high-risk vulnerabilities detected on external perimeter.*")
    lines.append("\n")

    # 7. Recommended Offensive Attack Vectors
    if attack_vectors:
        lines.append("## 5. Potential Attack Vectors & Lateral Movement Opportunities")
        for vec in attack_vectors:
            lines.append(f"### Vector: {vec.get('vector_name')}")
            lines.append(f"- **Likelihood:** {vec.get('likelihood')} | **Impact:** {vec.get('impact')}")
            lines.append("**Operational Steps:**")
            for step in vec.get("steps", []):
                lines.append(f"1. {step}")
            lines.append("")

    # 8. People & Organizational OSINT
    lines.append("## 6. People & Organizational Intelligence")
    lines.append(f"- **Inferred Email Pattern:** `{people.get('email_pattern', 'Unknown')}`")
    lines.append(f"- **Confirmed Employee Contacts:** {people.get('confirmed_count', 0)}")
    lines.append(f"- **Inferred Staff Records:** {people.get('inferred_count', 0)}\n")

    people_list = people.get("people", [])
    if people_list:
        lines.append("| Name | Email Address | Status | Confidence | Sources |")
        lines.append("|---|---|---|---|---|")
        for person in people_list[:25]:
            status_tag = "Inferred" if person.get("inferred") else "Confirmed"
            sources_str = ", ".join(person.get("sources", []))
            lines.append(f"| {person.get('name') or 'N/A'} | `{person.get('email')}` | {status_tag} | {person.get('confidence')}% | {sources_str} |")
    else:
        lines.append("*No public employee contact data exposed across queried sources.*")
    lines.append("\n")

    lines.append("---\n*End of Report — R7 Red Team Intelligence Platform*")
    return "\n".join(lines)
